{{! This file is processed with handlebars. The tag helper will return the provided string in double braces}}
version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: icon.svg
  required:
    - build
    - app-repo
    - testscript-repo
  info:
    git url: >-
      [https://github.com/sam-almighty/simple-toolchain](https://github.com/sam-almighty/simple-toolchain)
    git branch: >-
      [master](https://github.com/sam-almighty/simple-toolchain/tree/master)
toolchain:
  name: {{name}}
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  testscript-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'testscript-repo-{{timestamp}}'
      repo_url: '{{testrepo}}'
      type: clone
      has_issues: true
      enable_traceability: true
  app-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'app-repo-{{timestamp}}'
      repo_url: '{{apprepo}}'
      type: clone
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - app-repo
        - testscript-repo
      name: '{{services.app-repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          APP_REPO: app-repo
          SCRIPT_REPO: testscript-repo
          PROD_SPACE_NAME: '{{prodspacename}}'
          PROD_ORG_NAME: '{{prodorgname}}'
          PROD_REGION_ID: '{{prodregion}}'
        execute: false
form:
  pipeline:
    parameters:
      prod-app-name: '{{prodappname}}'
    schema:
      $ref: deploy.json
